//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaPhuong
    {
        public string MaDP { get; set; }
        public string TenDP { get; set; }
        public int SoCaNhiemMoi { get; set; }
        public int MaTT { get; set; }
    
        public virtual TrangThai TrangThai { get; set; }
    }
}
